name = "backend"
compatibility_date = "2024-08-21"

[vars]
DATABASE_URL = "prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiN2NmMTU5Y2UtYzNiMS00MjFjLTkzNTItZTgzMzc1NWJiZjY3IiwidGVuYW50X2lkIjoiOWI2Nzc3NjU3NTdhMThiYjQwYTEzYjU0ZDI5YjcwOGQwYzUzNjMzNTI0NmIxNWJmNDg2Y2Y5OTVlNzM0ZDZjNCIsImludGVybmFsX3NlY3JldCI6ImJlODE5NDdlLThjZDUtNGI4Ni05ZDU0LTQxNmU2ODhmOGQxOCJ9.FK2H3sHEHOg87V2rMgo6jfsM_k69ogsN6_py5JquN64"